### PR TITLE
Fix error handling on Linux when checking for feature availability

### LINKED ISSUE #2: UnhandledPromiseRejectionWarning on Linux
Hi,

I'm using ArchLinux and running `watchlist` consistently fails with the following error:

```
↳ watchlist src/ -- echo "hello"
(node:161871) UnhandledPromiseRejectionWarning: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at watch (fs.js:1470:11)
    at setup (/home/madx/tmp/watchlist/node_modules/watchlist/dist/index.js:30:17)
    at watch (/home/madx/tmp/watchlist/node_modules/watchlist/dist/index.js:77:18)
    at Object.<anonymous> (/home/madx/tmp/watchlist/node_modules/watchlist/bin.js:58:2)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:161871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:161871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by madx**
This fixes #2

### CODE REVIEW

**Comment by madx** [comment]
I'm sorry if my first initial issue/PR sounded a bit sarcastic or inappropriate, I should have taken a few more minutes to investigate further myself ;)

**Comment by lukeed** [comment]
Not a problem! Thank you :)
Ignore my #2 comment haha

**Comment by lukeed** [comment]
Will release this once I get back to a computer. Should be about an hour

**Comment by madx** [comment]
Thanks, that's great :+1:

**Pull request merged**
